import React, { useEffect, useState } from 'react';
import { Download, FileText, Zap, CheckCircle, ArrowRight, Play, Star, Users, Clock, BookOpen } from 'lucide-react';
import { usePageTitle } from '../hooks/usePageTitle';

const SeeSciDraftInAction: React.FC = () => {
  usePageTitle('See SciDraft in Action - Live Demo & Examples | SciDraft');
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
  }, []);

  const sampleReports = [
    {
      id: 1,
      title: "Chemistry: Acid-Base Titration",
      subject: "Chemistry",
      description: "Complete analysis of titration experiment with calculations and error analysis.",
      manualUrl: "/samples/chemistry-manual.pdf",
      reportUrl: "/samples/chemistry-report.pdf",
      previewImage: "https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=chemistry%20laboratory%20titration%20setup%20with%20burette%20and%20conical%20flask%20scientific%20illustration&image_size=landscape_4_3"
    },
    {
      id: 2,
      title: "Biology: Microscopy Analysis",
      subject: "Biology",
      description: "Detailed observation and analysis of plant and animal cell structures.",
      manualUrl: "/samples/biology-manual.pdf",
      reportUrl: "/samples/biology-report.pdf",
      previewImage: "https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=microscope%20with%20biological%20specimens%20cells%20scientific%20laboratory%20illustration&image_size=landscape_4_3"
    },
    {
      id: 3,
      title: "Physics: Projectile Motion",
      subject: "Physics",
      description: "Mathematical analysis of projectile motion with trajectory calculations.",
      manualUrl: "/samples/physics-manual.pdf",
      reportUrl: "/samples/physics-report.pdf",
      previewImage: "https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=physics%20projectile%20motion%20trajectory%20laboratory%20setup%20scientific%20diagram&image_size=landscape_4_3"
    }
  ];

  const features = [
    "AI-powered content generation",
    "Professional formatting",
    "Automatic calculations",
    "Citation management",
    "Multiple export formats",
    "Quality assurance checks"
  ];

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Animated Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-600/20 via-purple-600/20 to-pink-600/20 animate-pulse"></div>
        <div className="absolute inset-0">
          <div className="absolute top-0 left-0 w-72 h-72 bg-blue-500/30 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob will-change-transform motion-reduce:animate-none"></div>
          <div className="absolute top-0 right-0 w-72 h-72 bg-purple-500/30 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000 will-change-transform motion-reduce:animate-none"></div>
          <div className="absolute bottom-0 left-0 w-72 h-72 bg-pink-500/30 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000 will-change-transform motion-reduce:animate-none"></div>
        </div>
      </div>
      {/* Header Section */}
      <div className="relative z-10">
        <div className={`backdrop-blur-xl bg-white/10 border-b border-white/20 transition-all duration-1000 will-change-transform motion-reduce:transition-none ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-10'}`}>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
            <div className="text-center">
              <div className="flex justify-center mb-6">
                <div className="bg-gradient-to-r from-blue-500/20 to-purple-500/20 backdrop-blur-sm p-4 rounded-full border border-white/30 shadow-2xl hover:scale-110 transition-transform duration-300">
                  <Play className="h-10 w-10 text-white" />
                </div>
              </div>
              <h1 className="text-5xl font-bold text-white mb-6 bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                See SciDraft in Action
              </h1>
              <p className="text-xl text-gray-200 max-w-3xl mx-auto leading-relaxed">
                Explore real examples of lab reports generated by SciDraft. 
                See how our AI transforms your experimental data into professional, 
                well-structured scientific documents.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Features Overview */}
        <div className={`mb-16 transition-all duration-1000 delay-200 will-change-transform motion-reduce:transition-none ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
          <h2 className="text-3xl font-bold text-white text-center mb-8 bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
            What Makes SciDraft Special
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '600ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-blue-500/20 to-cyan-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <Zap className="h-6 w-6 text-blue-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">AI-Powered Writing</h3>
              </div>
              <p className="text-gray-200">
                Generate comprehensive lab reports with intelligent content suggestions and scientific accuracy.
              </p>
            </div>

            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '700ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-green-500/20 to-emerald-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <CheckCircle className="h-6 w-6 text-green-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">Quality Assurance</h3>
              </div>
              <p className="text-gray-200">
                Built-in checks for scientific methodology, data analysis, and proper formatting.
              </p>
            </div>

            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '800ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-purple-500/20 to-pink-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <Clock className="h-6 w-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">Time Efficient</h3>
              </div>
              <p className="text-gray-200">
                Complete your lab reports in minutes, not hours, with our streamlined workflow.
              </p>
            </div>

            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '900ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-orange-500/20 to-red-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <FileText className="h-6 w-6 text-orange-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">Professional Format</h3>
              </div>
              <p className="text-gray-200">
                Industry-standard formatting that meets academic and professional requirements.
              </p>
            </div>

            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '1000ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-red-500/20 to-pink-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <Star className="h-6 w-6 text-red-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">Data Visualization</h3>
              </div>
              <p className="text-gray-200">
                Automatic generation of charts, graphs, and tables from your experimental data.
              </p>
            </div>

            <div className={`backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '1100ms' }}>
              <div className="flex items-center mb-4">
                <div className="bg-gradient-to-r from-indigo-500/20 to-blue-500/20 backdrop-blur-sm p-2 rounded-lg mr-3 border border-white/30">
                  <Users className="h-6 w-6 text-indigo-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">Collaboration</h3>
              </div>
              <p className="text-gray-200">
                Share and collaborate on reports with team members and supervisors in real-time.
              </p>
            </div>
          </div>
        </div>

        {/* Sample Reports */}
        <div className={`space-y-16 transition-all duration-1000 delay-400 will-change-transform motion-reduce:transition-none ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
          <h2 className="text-3xl font-bold text-white text-center mb-12 bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
            Sample Reports & Examples
          </h2>
          
          {sampleReports.map((report, index) => (
            <div 
              key={report.id} 
              className={`backdrop-blur-xl bg-white/10 rounded-2xl border border-white/20 overflow-hidden hover:bg-white/20 transition-all duration-500 hover:scale-105 hover:shadow-2xl group ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}
              style={{ transitionDelay: `${600 + index * 200}ms` }}
            >
              <div className="p-8">
                <div className="flex flex-col lg:flex-row gap-8">
                  {/* Left Column - Report Info */}
                  <div className="lg:w-1/2 space-y-6">
                    <div>
                      <div className="inline-block px-3 py-1 bg-gradient-to-r from-blue-500/20 to-purple-500/20 backdrop-blur-sm text-cyan-300 text-sm font-medium rounded-full mb-3 border border-white/30">
                        {report.subject}
                      </div>
                      <h3 className="text-2xl font-bold text-white mb-3 group-hover:text-cyan-300 transition-colors duration-300">
                        {report.title}
                      </h3>
                      <p className="text-gray-300 text-lg leading-relaxed">
                        {report.description}
                      </p>
                    </div>
                    
                    <div className="space-y-4">
                      <h4 className="text-lg font-semibold text-white">
                        Download Examples:
                      </h4>
                      <div className="flex flex-col sm:flex-row gap-3">
                        <a
                          href={report.manualUrl}
                          className="inline-flex items-center justify-center px-4 py-2 bg-white/10 text-gray-300 rounded-lg hover:bg-white/20 hover:text-white transition-all duration-300 font-medium border border-white/20 hover:scale-105"
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          Lab Manual
                        </a>
                        <a
                          href={report.reportUrl}
                          className="inline-flex items-center justify-center px-4 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-300 font-medium hover:scale-105 shadow-lg"
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          <Download className="h-4 w-4 mr-2" />
                          Generated Report
                        </a>
                      </div>
                    </div>
                  </div>
                  
                  {/* Right Column - Preview */}
                  <div className="lg:w-1/2">
                    <div className="bg-white/5 backdrop-blur-sm rounded-xl p-6 h-full flex items-center justify-center border border-white/10 group-hover:bg-white/10 transition-all duration-300">
                      <div className="text-center">
                        <img
                          src={report.previewImage}
                          alt={`${report.title} preview`}
                          className="w-full max-w-md mx-auto rounded-lg shadow-md mb-4 group-hover:scale-105 transition-transform duration-300"
                          loading="lazy"
                        />
                        <p className="text-gray-400 text-sm">
                          Preview of {report.subject.toLowerCase()} experiment setup
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Process Overview */}
        <div className="relative z-10 py-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className={`text-center mb-12 transition-all duration-1000 delay-1000 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
              <h2 className="text-3xl font-bold text-white mb-4 bg-gradient-to-r from-cyan-400 via-blue-400 to-purple-400 bg-clip-text text-transparent">
                How It Works
              </h2>
              <p className="text-xl text-gray-200 max-w-3xl mx-auto">
                Create professional lab reports in three simple steps
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className={`text-center backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '1200ms' }}>
                <div className="bg-gradient-to-r from-blue-500 to-cyan-500 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg animate-glow">
                  <span className="text-2xl font-bold text-white">1</span>
                </div>
                <h3 className="text-xl font-semibold text-white mb-2">Input Your Data</h3>
                <p className="text-gray-200">
                  Enter your experimental data, observations, and methodology details
                </p>
              </div>

              <div className={`text-center backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '1300ms' }}>
                <div className="bg-gradient-to-r from-green-500 to-emerald-500 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg animate-glow">
                  <span className="text-2xl font-bold text-white">2</span>
                </div>
                <h3 className="text-xl font-semibold text-white mb-2">AI Processing</h3>
                <p className="text-gray-200">
                  Our AI analyzes your data and generates comprehensive report sections
                </p>
              </div>

              <div className={`text-center backdrop-blur-xl bg-white/10 border border-white/20 p-6 rounded-lg shadow-2xl hover:bg-white/20 transition-all duration-500 hover:scale-105 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`} style={{ transitionDelay: '1400ms' }}>
                <div className="bg-gradient-to-r from-purple-500 to-pink-500 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg animate-glow">
                  <span className="text-2xl font-bold text-white">3</span>
                </div>
                <h3 className="text-xl font-semibold text-white mb-2">Download & Share</h3>
                <p className="text-gray-200">
                  Get your professionally formatted report ready for submission
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Call to Action */}
        <div className={`relative z-10 py-16 transition-all duration-1000 delay-1500 ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <div className="backdrop-blur-xl bg-gradient-to-r from-blue-500/20 to-purple-500/20 border border-white/30 rounded-2xl p-8 shadow-2xl hover:from-blue-500/30 hover:to-purple-500/30 transition-all duration-500">
              <h2 className="text-3xl font-bold text-white mb-4 bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                Ready to Transform Your Lab Reports?
              </h2>
              <p className="text-xl text-gray-200 mb-8">
                Join thousands of students and researchers who trust SciDraft for their scientific writing needs.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <a
                  href="/new-report"
                  className="inline-flex items-center px-8 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-300 hover:scale-105 shadow-lg backdrop-blur-sm border border-white/20"
                >
                  <FileText className="h-5 w-5 mr-2" />
                  Start Writing Now
                </a>
                <a
                  href="/lab-report-guide"
                  className="inline-flex items-center px-8 py-3 bg-white/10 backdrop-blur-sm border-2 border-white/30 text-white font-semibold rounded-lg hover:bg-white/20 transition-all duration-300 hover:scale-105 shadow-lg"
                >
                  <BookOpen className="h-5 w-5 mr-2" />
                  Learn More
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SeeSciDraftInAction;